### ISSUE TITLE
Not able to change the net balance of  customer after deposit and withdraw

### ISSUE THREAD

**Issue by Akashtiwari123** [Akashtiwari123/Java-Programs#2]
In banking System folder i  am unable to use the **reference variable** to fetch and set the new balance of customer

**Comment by Mayureshvartak** [comment]
See made changes to your code and uploaded 
Now run the file your code will get execute for net deposit.

**Comment by Akashtiwari123** [comment]
yet it is not going to class A for deposit ,its doing everything in customer class .
